model:
  exe_path: ../inference/cpp_tensorrt/build/camera_tensorrt
  engine_path: ../inference/models/yolo11n_person.engine
  runtime_config_dir: ../inference/configs/runtime
  prestart_mode: false
  settle_single_frame: false
  jpeg_quality: 95
  version: '1.0'
  camera_id: cam_demo_001
  detect_enable: true
  infer_target: all
  model_name: YOLO11
  imgsz: 640
  conf_thres: 0.5
  iou_thres: 0.1
  enter_frames: 3
  exit_frames: 5
  person_class_ids:
  - 0
  rois:
  - roi_id: hazard_1
    name: ROI1
    enabled: true
    roi_type: forbidden_zone
    judge_method: foot_point
    coordinate_mode: normalized
    polygon:
    - - 0.6371
      - 0.2475
    - - 0.9282
      - 0.2475
    - - 0.9282
      - 0.7271
    - - 0.6371
      - 0.7271
    overlap_thres: 0.1
    target: all
test:
  hot_reload: true
  image: /home/jetson/code/Cam_flaskvue/inference/test_img/image.png
  interval: 0.5
  save_path: hot_reload_result.jpg
  show: false
