model:
  model_path: ../inference/models
  runtime_config_dir: ../inference/configs/runtime
  prestart_mode: false
  settle_single_frame: false
  jpeg_quality: 95
  version: '1.0'
  camera_id: cam_demo_001
  detect_enable: true
  infer_target: all
  model_name: Asva_person_v0518
  imgsz: 640
  conf_thres: 0.5
  iou_thres: 0.1
  enter_frames: 3
  exit_frames: 5
  class_name:
  - person
  person_class_ids:
  - 0
  rois:
  - roi_id: hazard_1
    name: ROI1
    enabled: true
    roi_type: forbidden_zone
    judge_method: overlap
    coordinate_mode: normalized
    polygon:
    - - 0.5661
      - 0.2039
    - - 0.9438
      - 0.2039
    - - 0.9438
      - 0.8198
    - - 0.5661
      - 0.8198
    overlap_thres: 0.01
    target: all
test:
  hot_reload: true
  image: ../inference/test_img/image.png
  interval: 0.5
  show: false
  save_path: ../outputs/python_tensorrt_result.jpg
model_names:
- Asva_person_v0518
exception_output:
  gpio:
  - 7
  output_level: 1
  duration: 0
record:
  duration_min: 1.0
